cc_test(
    name = "tests",
    srcs = glob(["*.cpp"]),
    deps = [
        "@com_google_googletest//:gtest_main",
        "//cpp_gmock_bank:Iserver",
        "//cpp_gmock_bank:icici_server",
        
    ]

)