cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = ["//cpp_stack:stack"],
)

cc_library(
    name = "stack",
    srcs = ["stack.cpp"],
    hdrs = ["stack.h"],
    visibility = ["//visibility:public"],
)