py_library(
    name = "calculator",
    srcs = ["calculator.py"]
    
)

py_test(
    name = "test_calculator",
    srcs = ["test_calculator.py"],
    deps = [
        "//python_project:calculator"
    ]
)